# GenerateCacertBundle.cmake
# Converts a PEM CA bundle into a C header with the raw bytes stored as a
# static unsigned char array.  The generated header is consumed by
# dns_over_https.cc on platforms (Orbis/Prospero) that cannot access the
# system certificate store at runtime.
#
# Usage (cmake script mode):
#   cmake -DCACERT_PEM=<path/to/cacert.pem>
#         -DCACERT_HEADER=<path/to/cacert_bundle.h>
#         -P GenerateCacertBundle.cmake

cmake_minimum_required(VERSION 3.10.2)

if(NOT CACERT_PEM)
    message(FATAL_ERROR "CACERT_PEM must be set to the PEM source file path")
endif()

if(NOT CACERT_HEADER)
    message(FATAL_ERROR "CACERT_HEADER must be set to the output header path")
endif()

if(NOT EXISTS "${CACERT_PEM}")
    message(FATAL_ERROR "CACERT_PEM file not found: ${CACERT_PEM}")
endif()

# Read file as lowercase hex string (two chars per byte)
file(READ "${CACERT_PEM}" _hex HEX)

# Insert "0x" prefix and "," suffix for each byte pair to build a C initialiser list
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _array "${_hex}")

# Byte count for the length constant
file(SIZE "${CACERT_PEM}" _size)

get_filename_component(_pem_name "${CACERT_PEM}" NAME)

# Create the output directory if it does not already exist
get_filename_component(_header_dir "${CACERT_HEADER}" DIRECTORY)
file(MAKE_DIRECTORY "${_header_dir}")

file(WRITE "${CACERT_HEADER}"
"// Auto-generated from ${_pem_name} at compile time
// DO NOT EDIT - This file is automatically generated
#ifndef CACERT_BUNDLE_H_
#define CACERT_BUNDLE_H_

#include <cstddef> // std::size_t

// Mozilla CA certificate bundle (PEM format) embedded at compile time
// for platforms that cannot access system certificate stores at runtime.
static const unsigned char g_CacertBundle[] = {
${_array}
};
static const std::size_t g_CacertBundleLen = ${_size};

#endif
")

message(STATUS "Generated cacert bundle header: ${CACERT_HEADER} (${_size} bytes)")
